
SRC_FILES=src/main.c src/insertion_sort.c src/heap_sort.c src/distribution_sort.c src/merge_sort.c src/quick_sort.c src/selection_sort.c src/input.c src/utils.c

BUILD_DIR=build

CC_FLAGS=	-W \
			-Wall \

all:
	gcc -o $(BUILD_DIR)/main $(SRC_FILES) $(CC_FLAGS)
