
ALG_DIR=src/algorithms/
INPUT_DIR=src/input/

SRC_FILES=src/main.c $(ALG_DIR)*.c $(INPUT_DIR)input.c src/utils.c

BUILD_DIR=build

CC_FLAGS=	-W \
			-Wall \

all:
	gcc -o $(BUILD_DIR)/main $(SRC_FILES) $(CC_FLAGS)
